/**
 * mockData.js
 * Curated real songs, artists, albums with actual YouTube video IDs.
 * This data is used as fallback when no YouTube API key is configured,
 * and as the "featured" seed data for the app.
 */

// ─── Songs ────────────────────────────────────────────────────────────────────
export const FEATURED_SONGS = [
  {
    id: 'yt_blindinglights',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    artistId: 'artist_weeknd',
    album: 'After Hours',
    albumId: 'album_afterhours',
    duration: 200,
    genre: 'Pop',
    year: 2019,
    thumbnail: 'https://i.ytimg.com/vi/4NRXx6U8ABQ/maxresdefault.jpg',
    videoId: '4NRXx6U8ABQ',
    plays: 9800000,
  },
  {
    id: 'yt_shapeofyou',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    artistId: 'artist_edsheeran',
    album: '÷ (Divide)',
    albumId: 'album_divide',
    duration: 234,
    genre: 'Pop',
    year: 2017,
    thumbnail: 'https://i.ytimg.com/vi/JGwWNGJdvx8/maxresdefault.jpg',
    videoId: 'JGwWNGJdvx8',
    plays: 12000000,
  },
  {
    id: 'yt_diewithasmile',
    title: 'Die With A Smile',
    artist: 'Lady Gaga & Bruno Mars',
    artistId: 'artist_ladygaga',
    album: 'Die With A Smile',
    albumId: 'album_diewithasmile',
    duration: 251,
    genre: 'Pop',
    year: 2024,
    thumbnail: 'https://i.ytimg.com/vi/kPa7bsKwL-c/maxresdefault.jpg',
    videoId: 'kPa7bsKwL-c',
    plays: 7500000,
  },
  {
    id: 'yt_flowers',
    title: 'Flowers',
    artist: 'Miley Cyrus',
    artistId: 'artist_mileycyrus',
    album: 'Endless Summer Vacation',
    albumId: 'album_endlesssummer',
    duration: 200,
    genre: 'Pop',
    year: 2023,
    thumbnail: 'https://i.ytimg.com/vi/G7KNmW9a75Y/maxresdefault.jpg',
    videoId: 'G7KNmW9a75Y',
    plays: 8200000,
  },
  {
    id: 'yt_espresso',
    title: 'Espresso',
    artist: 'Sabrina Carpenter',
    artistId: 'artist_sabrinacarpenter',
    album: 'Short n\' Sweet',
    albumId: 'album_shortnsweet',
    duration: 175,
    genre: 'Pop',
    year: 2024,
    thumbnail: 'https://i.ytimg.com/vi/eVli-tstM5E/maxresdefault.jpg',
    videoId: 'eVli-tstM5E',
    plays: 9100000,
  },
  {
    id: 'yt_asitwas',
    title: 'As It Was',
    artist: 'Harry Styles',
    artistId: 'artist_harrystyles',
    album: "Harry's House",
    albumId: 'album_harryshouse',
    duration: 167,
    genre: 'Pop',
    year: 2022,
    thumbnail: 'https://i.ytimg.com/vi/H5v3kku4y6Q/maxresdefault.jpg',
    videoId: 'H5v3kku4y6Q',
    plays: 11000000,
  },
  {
    id: 'yt_badhabits',
    title: 'Bad Habits',
    artist: 'Ed Sheeran',
    artistId: 'artist_edsheeran',
    album: '= (Equals)',
    albumId: 'album_equals',
    duration: 231,
    genre: 'Pop',
    year: 2021,
    thumbnail: 'https://i.ytimg.com/vi/orJSJGHjBLI/maxresdefault.jpg',
    videoId: 'orJSJGHjBLI',
    plays: 8900000,
  },
  {
    id: 'yt_cruel_summer',
    title: 'Cruel Summer',
    artist: 'Taylor Swift',
    artistId: 'artist_taylorswift',
    album: 'Lover',
    albumId: 'album_lover',
    duration: 178,
    genre: 'Pop',
    year: 2019,
    thumbnail: 'https://i.ytimg.com/vi/ic8j13piAhQ/maxresdefault.jpg',
    videoId: 'ic8j13piAhQ',
    plays: 10500000,
  },
  {
    id: 'yt_levitating',
    title: 'Levitating',
    artist: 'Dua Lipa',
    artistId: 'artist_dualipa',
    album: 'Future Nostalgia',
    albumId: 'album_futurenostalgia',
    duration: 203,
    genre: 'Pop',
    year: 2020,
    thumbnail: 'https://i.ytimg.com/vi/TUVcZfQe-Kw/maxresdefault.jpg',
    videoId: 'TUVcZfQe-Kw',
    plays: 9400000,
  },
  {
    id: 'yt_heat_waves',
    title: 'Heat Waves',
    artist: 'Glass Animals',
    artistId: 'artist_glassanimals',
    album: 'Dreamland',
    albumId: 'album_dreamland',
    duration: 238,
    genre: 'Indie',
    year: 2020,
    thumbnail: 'https://i.ytimg.com/vi/mRD0-GxqHVo/maxresdefault.jpg',
    videoId: 'mRD0-GxqHVo',
    plays: 7800000,
  },
  {
    id: 'yt_stay',
    title: 'Stay',
    artist: 'The Kid LAROI & Justin Bieber',
    artistId: 'artist_kidlaroi',
    album: 'F*CK LOVE 3',
    albumId: 'album_fucklove3',
    duration: 141,
    genre: 'Pop',
    year: 2021,
    thumbnail: 'https://i.ytimg.com/vi/kTJczUoc26U/maxresdefault.jpg',
    videoId: 'kTJczUoc26U',
    plays: 8600000,
  },
  {
    id: 'yt_save_your_tears',
    title: 'Save Your Tears',
    artist: 'The Weeknd',
    artistId: 'artist_weeknd',
    album: 'After Hours',
    albumId: 'album_afterhours',
    duration: 215,
    genre: 'Pop',
    year: 2020,
    thumbnail: 'https://i.ytimg.com/vi/XXYlFuWiqWI/maxresdefault.jpg',
    videoId: 'XXYlFuWiqWI',
    plays: 8300000,
  },
  {
    id: 'yt_bad_guy',
    title: 'bad guy',
    artist: 'Billie Eilish',
    artistId: 'artist_billieeilish',
    album: 'When We All Fall Asleep, Where Do We Go?',
    albumId: 'album_wwafawdwg',
    duration: 194,
    genre: 'Pop',
    year: 2019,
    thumbnail: 'https://i.ytimg.com/vi/DyDfgMOUjCI/maxresdefault.jpg',
    videoId: 'DyDfgMOUjCI',
    plays: 11500000,
  },
  {
    id: 'yt_happier',
    title: 'Happier',
    artist: 'Olivia Rodrigo',
    artistId: 'artist_oliviarodrigo',
    album: 'SOUR',
    albumId: 'album_sour',
    duration: 218,
    genre: 'Pop',
    year: 2021,
    thumbnail: 'https://i.ytimg.com/vi/agSENHsHrVY/maxresdefault.jpg',
    videoId: 'agSENHsHrVY',
    plays: 7200000,
  },
  {
    id: 'yt_drivers_license',
    title: "drivers license",
    artist: 'Olivia Rodrigo',
    artistId: 'artist_oliviarodrigo',
    album: 'SOUR',
    albumId: 'album_sour',
    duration: 242,
    genre: 'Pop',
    year: 2021,
    thumbnail: 'https://i.ytimg.com/vi/ZmDBbnmKpqQ/maxresdefault.jpg',
    videoId: 'ZmDBbnmKpqQ',
    plays: 9700000,
  },
  {
    id: 'yt_anti_hero',
    title: 'Anti-Hero',
    artist: 'Taylor Swift',
    artistId: 'artist_taylorswift',
    album: 'Midnights',
    albumId: 'album_midnights',
    duration: 200,
    genre: 'Pop',
    year: 2022,
    thumbnail: 'https://i.ytimg.com/vi/b1kbLwvqugk/maxresdefault.jpg',
    videoId: 'b1kbLwvqugk',
    plays: 10200000,
  },
  {
    id: 'yt_uptown_funk',
    title: 'Uptown Funk',
    artist: 'Mark Ronson ft. Bruno Mars',
    artistId: 'artist_brunomars',
    album: 'Uptown Special',
    albumId: 'album_uptownspecial',
    duration: 270,
    genre: 'Funk',
    year: 2014,
    thumbnail: 'https://i.ytimg.com/vi/OPf0YbXqDm0/maxresdefault.jpg',
    videoId: 'OPf0YbXqDm0',
    plays: 13000000,
  },
  {
    id: 'yt_dynamite',
    title: 'Dynamite',
    artist: 'BTS',
    artistId: 'artist_bts',
    album: 'BE',
    albumId: 'album_be_bts',
    duration: 199,
    genre: 'K-Pop',
    year: 2020,
    thumbnail: 'https://i.ytimg.com/vi/gdZLi9oWNZg/maxresdefault.jpg',
    videoId: 'gdZLi9oWNZg',
    plays: 12500000,
  },
  {
    id: 'yt_butter',
    title: 'Butter',
    artist: 'BTS',
    artistId: 'artist_bts',
    album: 'Butter',
    albumId: 'album_butter',
    duration: 164,
    genre: 'K-Pop',
    year: 2021,
    thumbnail: 'https://i.ytimg.com/vi/WMweEpGlu_U/maxresdefault.jpg',
    videoId: 'WMweEpGlu_U',
    plays: 11200000,
  },
  {
    id: 'yt_night_changes',
    title: 'Night Changes',
    artist: 'One Direction',
    artistId: 'artist_onedirection',
    album: 'FOUR',
    albumId: 'album_four',
    duration: 233,
    genre: 'Pop',
    year: 2014,
    thumbnail: 'https://i.ytimg.com/vi/syFZfO_wfMQ/maxresdefault.jpg',
    videoId: 'syFZfO_wfMQ',
    plays: 8100000,
  },
];

// ─── Artists ───────────────────────────────────────────────────────────────────
export const ARTISTS = [
  {
    id: 'artist_taylorswift',
    name: 'Taylor Swift',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/191125_Taylor_Swift_at_the_2019_American_Music_Awards_%28cropped%29.png/440px-191125_Taylor_Swift_at_the_2019_American_Music_Awards_%28cropped%29.png',
    banner: 'https://i.ytimg.com/vi/ic8j13piAhQ/maxresdefault.jpg',
    genres: ['Pop', 'Country', 'Indie Pop'],
    monthlyListeners: 95000000,
    bio: 'Taylor Alison Swift is an American singer-songwriter. Her narrative songwriting, which often centers around her personal life, has received widespread media coverage and critical acclaim. Born in 1989 in West Reading, Pennsylvania.',
    verified: true,
    followers: 70000000,
    popularSongIds: ['yt_cruel_summer', 'yt_anti_hero', 'yt_shakeItOff'],
    albumIds: ['album_lover', 'album_midnights'],
  },
  {
    id: 'artist_weeknd',
    name: 'The Weeknd',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/The_Weeknd_-_Openair_Frauenfeld_2017_%28cropped%29.jpg/440px-The_Weeknd_-_Openair_Frauenfeld_2017_%28cropped%29.jpg',
    banner: 'https://i.ytimg.com/vi/4NRXx6U8ABQ/maxresdefault.jpg',
    genres: ['R&B', 'Pop', 'Synth-pop'],
    monthlyListeners: 88000000,
    bio: 'Abel Makkonen Tesfaye, known professionally as the Weeknd, is a Canadian singer, songwriter, and record producer. Born in 1990 in Toronto, Ontario. Known for dark, introspective R&B music.',
    verified: true,
    followers: 55000000,
    popularSongIds: ['yt_blindinglights', 'yt_save_your_tears'],
    albumIds: ['album_afterhours'],
  },
  {
    id: 'artist_edsheeran',
    name: 'Ed Sheeran',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Ed_Sheeran_-_Lucca_Summer_Festival_2019_%28cropped%29.jpg/440px-Ed_Sheeran_-_Lucca_Summer_Festival_2019_%28cropped%29.jpg',
    banner: 'https://i.ytimg.com/vi/JGwWNGJdvx8/maxresdefault.jpg',
    genres: ['Pop', 'Acoustic', 'Indie Folk'],
    monthlyListeners: 82000000,
    bio: 'Edward Christopher Sheeran is an English singer-songwriter. Born in 1991 in Halifax, West Yorkshire. Known for his guitar-driven pop sound and record-breaking singles.',
    verified: true,
    followers: 60000000,
    popularSongIds: ['yt_shapeofyou', 'yt_badhabits'],
    albumIds: ['album_divide', 'album_equals'],
  },
  {
    id: 'artist_billieeilish',
    name: 'Billie Eilish',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Billie_Eilish_2024_%28cropped%29.jpg/440px-Billie_Eilish_2024_%28cropped%29.jpg',
    banner: 'https://i.ytimg.com/vi/DyDfgMOUjCI/maxresdefault.jpg',
    genres: ['Pop', 'Electropop', 'Indie Pop'],
    monthlyListeners: 73000000,
    bio: 'Billie Eilish Pirate Baird O\'Connell is an American singer and songwriter. Born in 2001 in Los Angeles. She became the youngest solo artist to debut at number one on the UK Albums Chart.',
    verified: true,
    followers: 62000000,
    popularSongIds: ['yt_bad_guy'],
    albumIds: ['album_wwafawdwg'],
  },
  {
    id: 'artist_brunomars',
    name: 'Bruno Mars',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Bruno_Mars_-_Moonshine_Jungle_Tour%2C_2014_%28cropped%29.jpg/440px-Bruno_Mars_-_Moonshine_Jungle_Tour%2C_2014_%28cropped%29.jpg',
    banner: 'https://i.ytimg.com/vi/OPf0YbXqDm0/maxresdefault.jpg',
    genres: ['Pop', 'R&B', 'Funk'],
    monthlyListeners: 70000000,
    bio: 'Peter Gene Hernandez, known professionally as Bruno Mars, is an American singer-songwriter and record producer. Born in 1985 in Honolulu, Hawaii. Known for his showmanship and retro-pop style.',
    verified: true,
    followers: 48000000,
    popularSongIds: ['yt_uptown_funk', 'yt_diewithasmile'],
    albumIds: ['album_uptownspecial'],
  },
  {
    id: 'artist_ladygaga',
    name: 'Lady Gaga',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Lady_Gaga_2022_promotional_photo.png/440px-Lady_Gaga_2022_promotional_photo.png',
    banner: 'https://i.ytimg.com/vi/kPa7bsKwL-c/maxresdefault.jpg',
    genres: ['Pop', 'Dance', 'Electronic'],
    monthlyListeners: 65000000,
    bio: 'Stefani Joanne Angelina Germanotta, known professionally as Lady Gaga, is an American singer, songwriter, and actress. Born in 1986 in New York City. Known for theatrical performances and fashion.',
    verified: true,
    followers: 50000000,
    popularSongIds: ['yt_diewithasmile'],
    albumIds: ['album_diewithasmile'],
  },
  {
    id: 'artist_coldplay',
    name: 'Coldplay',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Coldplay_2021.png/440px-Coldplay_2021.png',
    banner: 'https://i.ytimg.com/vi/dvgZkm1xWPE/maxresdefault.jpg',
    genres: ['Rock', 'Alternative', 'Pop Rock'],
    monthlyListeners: 78000000,
    bio: 'Coldplay are a British rock band formed in London in 1997. The band consists of Chris Martin, Jonny Buckland, Guy Berryman, and Will Champion. Known for anthemic stadium rock.',
    verified: true,
    followers: 52000000,
    popularSongIds: [],
    albumIds: [],
  },
  {
    id: 'artist_dualipa',
    name: 'Dua Lipa',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Dua_Lipa_2022_Cropped.jpg/440px-Dua_Lipa_2022_Cropped.jpg',
    banner: 'https://i.ytimg.com/vi/TUVcZfQe-Kw/maxresdefault.jpg',
    genres: ['Pop', 'Dance Pop', 'Disco'],
    monthlyListeners: 80000000,
    bio: 'Dua Lipa is an English and Albanian singer and songwriter. Born in 1995 in London. Known for her powerful vocals and disco-influenced pop music.',
    verified: true,
    followers: 58000000,
    popularSongIds: ['yt_levitating'],
    albumIds: ['album_futurenostalgia'],
  },
  {
    id: 'artist_oliviarodrigo',
    name: 'Olivia Rodrigo',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Olivia_Rodrigo_2022.jpg/440px-Olivia_Rodrigo_2022.jpg',
    banner: 'https://i.ytimg.com/vi/ZmDBbnmKpqQ/maxresdefault.jpg',
    genres: ['Pop', 'Indie Pop', 'Bedroom Pop'],
    monthlyListeners: 68000000,
    bio: 'Olivia Isabel Rodrigo is an American singer-songwriter and actress. Born in 2003 in Temecula, California. Known for emotionally raw songwriting.',
    verified: true,
    followers: 45000000,
    popularSongIds: ['yt_drivers_license', 'yt_happier'],
    albumIds: ['album_sour'],
  },
  {
    id: 'artist_bts',
    name: 'BTS',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/BTS_at_the_2019_Melon_Music_Awards.jpg/440px-BTS_at_the_2019_Melon_Music_Awards.jpg',
    banner: 'https://i.ytimg.com/vi/gdZLi9oWNZg/maxresdefault.jpg',
    genres: ['K-Pop', 'Pop', 'Hip-Hop'],
    monthlyListeners: 62000000,
    bio: 'BTS (Bangtan Sonyeondan) is a South Korean boy band formed in Seoul in 2013. Consisting of RM, Jin, Suga, J-Hope, Jimin, V, and Jungkook.',
    verified: true,
    followers: 72000000,
    popularSongIds: ['yt_dynamite', 'yt_butter'],
    albumIds: ['album_be_bts', 'album_butter'],
  },
];

// ─── Albums ────────────────────────────────────────────────────────────────────
export const ALBUMS = [
  {
    id: 'album_afterhours',
    title: 'After Hours',
    artist: 'The Weeknd',
    artistId: 'artist_weeknd',
    year: 2020,
    genre: 'R&B',
    cover: 'https://upload.wikimedia.org/wikipedia/en/c/c1/The_Weeknd_-_After_Hours.png',
    songIds: ['yt_blindinglights', 'yt_save_your_tears'],
  },
  {
    id: 'album_divide',
    title: '÷ (Divide)',
    artist: 'Ed Sheeran',
    artistId: 'artist_edsheeran',
    year: 2017,
    genre: 'Pop',
    cover: 'https://upload.wikimedia.org/wikipedia/en/4/45/Divide_cover.png',
    songIds: ['yt_shapeofyou'],
  },
  {
    id: 'album_lover',
    title: 'Lover',
    artist: 'Taylor Swift',
    artistId: 'artist_taylorswift',
    year: 2019,
    genre: 'Pop',
    cover: 'https://upload.wikimedia.org/wikipedia/en/c/cd/Taylor_Swift_-_Lover.png',
    songIds: ['yt_cruel_summer'],
  },
  {
    id: 'album_midnights',
    title: 'Midnights',
    artist: 'Taylor Swift',
    artistId: 'artist_taylorswift',
    year: 2022,
    genre: 'Pop',
    cover: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Midnights_-_3am_Edition.png',
    songIds: ['yt_anti_hero'],
  },
  {
    id: 'album_wwafawdwg',
    title: 'When We All Fall Asleep, Where Do We Go?',
    artist: 'Billie Eilish',
    artistId: 'artist_billieeilish',
    year: 2019,
    genre: 'Pop',
    cover: 'https://upload.wikimedia.org/wikipedia/en/3/38/When_We_All_Fall_Asleep%2C_Where_Do_We_Go%3F.png',
    songIds: ['yt_bad_guy'],
  },
  {
    id: 'album_futurenostalgia',
    title: 'Future Nostalgia',
    artist: 'Dua Lipa',
    artistId: 'artist_dualipa',
    year: 2020,
    genre: 'Pop',
    cover: 'https://upload.wikimedia.org/wikipedia/en/f/f5/Dua_Lipa_-_Future_Nostalgia_%28Official_Album_Cover%29.png',
    songIds: ['yt_levitating'],
  },
  {
    id: 'album_sour',
    title: 'SOUR',
    artist: 'Olivia Rodrigo',
    artistId: 'artist_oliviarodrigo',
    year: 2021,
    genre: 'Pop',
    cover: 'https://upload.wikimedia.org/wikipedia/en/b/b4/Olivia_Rodrigo_-_Sour_%28Official_Album_Cover%29.png',
    songIds: ['yt_drivers_license', 'yt_happier'],
  },
  {
    id: 'album_equals',
    title: '= (Equals)',
    artist: 'Ed Sheeran',
    artistId: 'artist_edsheeran',
    year: 2021,
    genre: 'Pop',
    cover: 'https://upload.wikimedia.org/wikipedia/en/d/d2/Ed_Sheeran_-_Equals.png',
    songIds: ['yt_badhabits'],
  },
  {
    id: 'album_shortnsweet',
    title: "Short n' Sweet",
    artist: 'Sabrina Carpenter',
    artistId: 'artist_sabrinacarpenter',
    year: 2024,
    genre: 'Pop',
    cover: 'https://upload.wikimedia.org/wikipedia/en/6/6a/Sabrina_Carpenter_-_Short_n%27_Sweet.png',
    songIds: ['yt_espresso'],
  },
  {
    id: 'album_be_bts',
    title: 'BE',
    artist: 'BTS',
    artistId: 'artist_bts',
    year: 2020,
    genre: 'K-Pop',
    cover: 'https://upload.wikimedia.org/wikipedia/en/8/86/BTS_-_BE.png',
    songIds: ['yt_dynamite'],
  },
];

// ─── Genres ────────────────────────────────────────────────────────────────────
export const GENRES = [
  { id: 'genre_pop', name: 'Pop', color: 'from-pink-500 to-rose-500', searchTerm: 'pop music' },
  { id: 'genre_hiphop', name: 'Hip-Hop', color: 'from-yellow-500 to-orange-500', searchTerm: 'hip hop music' },
  { id: 'genre_rock', name: 'Rock', color: 'from-red-600 to-red-900', searchTerm: 'rock music' },
  { id: 'genre_jazz', name: 'Jazz', color: 'from-blue-600 to-indigo-800', searchTerm: 'jazz music' },
  { id: 'genre_lofi', name: 'Lo-fi', color: 'from-purple-500 to-indigo-600', searchTerm: 'lofi hip hop beats' },
  { id: 'genre_classical', name: 'Classical', color: 'from-amber-600 to-yellow-700', searchTerm: 'classical music' },
  { id: 'genre_edm', name: 'EDM', color: 'from-cyan-400 to-blue-600', searchTerm: 'edm electronic dance music' },
  { id: 'genre_rnb', name: 'R&B', color: 'from-violet-500 to-purple-700', searchTerm: 'r&b soul music' },
  { id: 'genre_country', name: 'Country', color: 'from-yellow-700 to-amber-800', searchTerm: 'country music' },
  { id: 'genre_indie', name: 'Indie', color: 'from-green-500 to-teal-600', searchTerm: 'indie alternative music' },
  { id: 'genre_kpop', name: 'K-Pop', color: 'from-pink-400 to-fuchsia-600', searchTerm: 'kpop korean pop music' },
  { id: 'genre_jpop', name: 'J-Pop', color: 'from-red-400 to-pink-500', searchTerm: 'jpop japanese pop music' },
  { id: 'genre_thaipop', name: 'Thai Pop', color: 'from-blue-400 to-sky-600', searchTerm: 'thai pop music' },
];

// ─── Curated Playlists ─────────────────────────────────────────────────────────
export const CURATED_PLAYLISTS = [
  {
    id: 'playlist_top50',
    name: 'Global Top 50',
    description: 'The most played tracks right now across the globe.',
    cover: 'https://i.ytimg.com/vi/4NRXx6U8ABQ/mqdefault.jpg',
    songIds: ['yt_blindinglights', 'yt_shapeofyou', 'yt_espresso', 'yt_anti_hero', 'yt_levitating', 'yt_diewithasmile', 'yt_flowers'],
    isOfficial: true,
  },
  {
    id: 'playlist_chill',
    name: 'Chill Vibes',
    description: 'Relax and unwind with these easy-going tracks.',
    cover: 'https://i.ytimg.com/vi/mRD0-GxqHVo/mqdefault.jpg',
    songIds: ['yt_heat_waves', 'yt_asitwas', 'yt_flowers', 'yt_levitating'],
    isOfficial: true,
  },
  {
    id: 'playlist_workout',
    name: 'Workout Bangers',
    description: 'High-energy tracks to power your workout session.',
    cover: 'https://i.ytimg.com/vi/OPf0YbXqDm0/mqdefault.jpg',
    songIds: ['yt_uptown_funk', 'yt_dynamite', 'yt_butter', 'yt_badhabits', 'yt_stay'],
    isOfficial: true,
  },
  {
    id: 'playlist_heartbreak',
    name: 'Heartbreak Anthems',
    description: 'For when you just need to feel it.',
    cover: 'https://i.ytimg.com/vi/ZmDBbnmKpqQ/mqdefault.jpg',
    songIds: ['yt_drivers_license', 'yt_happier', 'yt_cruel_summer', 'yt_night_changes'],
    isOfficial: true,
  },
  {
    id: 'playlist_kpop',
    name: 'K-Pop Hits',
    description: 'The biggest K-Pop hits from BTS and more.',
    cover: 'https://i.ytimg.com/vi/gdZLi9oWNZg/mqdefault.jpg',
    songIds: ['yt_dynamite', 'yt_butter'],
    isOfficial: true,
  },
  {
    id: 'playlist_throwback',
    name: 'Throwback Jams',
    description: 'Classic hits that never get old.',
    cover: 'https://i.ytimg.com/vi/OPf0YbXqDm0/mqdefault.jpg',
    songIds: ['yt_uptown_funk', 'yt_shapeofyou', 'yt_night_changes', 'yt_bad_guy'],
    isOfficial: true,
  },
];

// ─── Mood Playlists ─────────────────────────────────────────────────────────────
export const MOOD_PLAYLISTS = [
  { id: 'mood_happy', name: 'Happy', emoji: '😊', color: 'from-yellow-400 to-orange-400', songIds: ['yt_uptown_funk', 'yt_dynamite', 'yt_espresso', 'yt_butter'] },
  { id: 'mood_sad', name: 'Sad', emoji: '😢', color: 'from-blue-500 to-indigo-600', songIds: ['yt_drivers_license', 'yt_happier', 'yt_night_changes'] },
  { id: 'mood_energetic', name: 'Energetic', emoji: '⚡', color: 'from-red-500 to-pink-500', songIds: ['yt_badhabits', 'yt_stay', 'yt_uptown_funk'] },
  { id: 'mood_romantic', name: 'Romantic', emoji: '💕', color: 'from-pink-400 to-rose-500', songIds: ['yt_cruel_summer', 'yt_asitwas', 'yt_levitating'] },
  { id: 'mood_chill', name: 'Chill', emoji: '😌', color: 'from-teal-400 to-cyan-500', songIds: ['yt_heat_waves', 'yt_flowers', 'yt_asitwas'] },
  { id: 'mood_focus', name: 'Focus', emoji: '🎯', color: 'from-purple-500 to-violet-600', songIds: ['yt_heat_waves', 'yt_levitating'] },
];

// ─── Helper: get song by id ────────────────────────────────────────────────────
export function getSongById(id) {
  return FEATURED_SONGS.find(s => s.id === id);
}

export function getArtistById(id) {
  return ARTISTS.find(a => a.id === id);
}

export function getAlbumById(id) {
  return ALBUMS.find(a => a.id === id);
}

export function getSongsByArtist(artistId) {
  return FEATURED_SONGS.filter(s => s.artistId === artistId);
}

export function getSongsByAlbum(albumId) {
  return FEATURED_SONGS.filter(s => s.albumId === albumId);
}

export function getSongsByGenre(genre) {
  return FEATURED_SONGS.filter(s => s.genre === genre);
}

export function formatDuration(seconds) {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${s.toString().padStart(2, '0')}`;
}

export function formatNumber(num) {
  if (num == null) return '0';
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`;
  if (num >= 1000) return `${(num / 1000).toFixed(0)}K`;
  return num.toString();
}
